# 1.3 Рекомендательные системы

Задание: **Вариант 5. Инициализация матриц для SVD**

Для матрицы оценок R размером 5×5 (задайте случайно) инициализируйте матрицы P (размер 5×d) и Q (размер d×5) со случайными значениями. d = 3. 

Рассчитайте предсказанную матрицу R_pred и среднеквадратическую ошибку (MSE) между исходной R и R_pred для ненулевых элементов.

---

In [3]:
import numpy as np

np.random.seed(42)

n_users = 5
n_items = 5
d = 3

R = np.random.randint(0, 6, size=(n_users, n_items))

print('Матрица R:')
print(R)

P = np.random.rand(n_users, d)
Q = np.random.rand(d, n_items)

print('\nМатрица P:')
print(P)
print('\nМатрица Q:')
print(Q)

R_pred = P @ Q

print('\nПредсказанная матрица R_pred:')
print(R_pred)

mask = R != 0
mse = np.mean((R[mask] - R_pred[mask]) ** 2)

print('\nMSE (по ненулевым элементам):', mse)

Матрица R:
[[3 4 2 4 4]
 [1 2 2 2 4]
 [3 2 5 4 1]
 [3 5 5 1 3]
 [4 0 3 1 5]]

Матрица P:
[[0.00706631 0.02306243 0.52477466]
 [0.39986097 0.04666566 0.97375552]
 [0.23277134 0.09060643 0.61838601]
 [0.38246199 0.98323089 0.46676289]
 [0.85994041 0.68030754 0.45049925]]

Матрица Q:
[[0.01326496 0.94220176 0.56328822 0.3854165  0.01596625]
 [0.23089383 0.24102547 0.68326352 0.60999666 0.83319491]
 [0.17336465 0.39106061 0.18223609 0.75536141 0.42515587]]

Предсказанная матрица R_pred:
[[0.09639608 0.21743521 0.11537096 0.413186   0.24243935]
 [0.18489374 0.76879475 0.43457532 0.91811626 0.45926375]
 [0.13121445 0.48298243 0.30571767 0.61208847 0.34211975]
 [0.31301547 0.77987262 0.97230317 1.09974939 1.02377644]
 [0.24658653 1.15038131 1.03132084 1.0867103  0.77209121]]

MSE (по ненулевым элементам): 8.212712680182298
